wavinfo: wavinfo.c file_handle.h file_handle.c header.h
	gcc -o wavinfo wavinfo.c file_handle.c -Wall

wavvol: wavvol.c file_handle.h file_handle.c header.h
	gcc -o wavvol wavvol.c file_handle.c -Wall

wavrev: wavrev.c file_handle.h file_handle.c header.h
	gcc -o wavrev wavrev.c file_handle.c -Wall